[tool.poetry]
name = "wiktionary-to-vocabulary-card"
version = "0.1.0"
description = ""
authors = ["Taiquan Liu <liutaiquan@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
